In [1]:
import numpy as np

print(np.__version__)

1.21.5


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [7]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [9]:
import numpy as np

arr = np.array([1, 0, 3, 4])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True  True]
bool


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [11]:
 import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)


[1 2 3 4 5 6 7 8]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [23]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 4, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]]), array([], shape=(6, 0), dtype=int32)]


In [31]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [32]:
# Find the indexes where the value is 4:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [33]:
# Find the indexes where the values are even:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [34]:
# Find the indexes where the values are odd:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [40]:
# Find the indexes where the value 7 should be inserted:
import numpy as np

arr = np.array([6, 8, 9, 7])

x = np.searchsorted(arr, 9, side = 'right')

print(x)

4


In [41]:
# To search for more than one value, use an array with the specified values.
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [42]:
# Create an array from the elements on index 0 and 2:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [43]:
# Create a filter array that will return only values higher than 42:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [45]:
# Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [49]:
# Generate a random integer from 0 to 100:
from numpy import random

x = random.randint(100)

print(x)

31


In [50]:
# Generate a random float from 0 to 1:

from numpy import random

x = random.rand()

print(x)

0.7552646237025304


In [51]:
# Generate a 1-D array containing 5 random integers from 0 to 100:

from numpy import random

x=random.randint(100, size=(5))

print(x)

[82 73 77 57 86]


In [52]:
"""
Generate a 2-D array with 3 rows, each row containing 5 random integers 
from 0 to 100:
""" 


from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[38 48 98 22 86]
 [57 69 76 25 51]
 [29  2 24 81 63]]


In [53]:
# Generate a 1-D array containing 5 random floats:

from numpy import random

x = random.rand(5)

print(x)

[0.08543822 0.64218408 0.39704255 0.57112053 0.95554737]


In [54]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.32797067 0.46365043 0.57653332 0.72905252 0.16822039]
 [0.40745885 0.03371762 0.67163051 0.14795692 0.04304159]
 [0.95985002 0.57758117 0.42378842 0.58197438 0.39944203]]


In [55]:
# Return one of the values in an array:

from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

9


In [56]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)


[[3 3 5 9 3]
 [7 7 9 5 9]
 [9 9 9 3 9]]


In [58]:
''' Generate a 1-D array containing 100 values, where each value has 
to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0
'''

from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 5 7 7 5 5 7 7 5 7 7 3 7 7 7 7 7 5 7 7 7 7 7 7 5 7 5 7 7 7 5 7 7 7 7 7
 3 5 7 7 7 7 7 5 7 7 7 7 5 7 7 5 7 7 7 7 7 5 5 7 7 7 5 7 7 7 7 5 7 5 5 5 7
 7 7 7 5 5 7 3 5 5 3 7 7 7 7 7 5 7 3 3 7 7 5 7 5 7 7]


In [59]:
# Same example as above, but return a 2-D array with 3 rows,
# each containing 5 values.

from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[5 7 7 3 7]
 [5 5 7 7 7]
 [7 7 7 5 7]]


In [60]:
# Randomly shuffle elements of following array:
# Cange the original array
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[4 1 2 3 5]


In [61]:
# Generate a random permutation of elements of following array:
# Keep the original array unchanged
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[2 4 5 3 1]


In [ ]:
import array
 
# Declare a list type object
list_object = [3, 4, 1, 5, 2]
 
# Declare an integer array object
array_object = array.array('i', [3, 4, 1, 5, 2])
 
print('Sorted list ->', sorted(list_object))
print('Sorted array ->', sorted(array_object))